-- Import all 60 stories in batches (Batch 1: Stories 1-20)
INSERT INTO interview_stories (
  star_l_id, role, organisation, year, theme, situation, task, action, result, lesson, 
  framing, tier, external_docs_url, score
) VALUES 
('SL001', 'Software Engineer', 'TechCorp', 2023, 'Software Engineer', 'Legacy system causing performance issues', 'Modernize architecture', 'Led migration to microservices', '50% performance improvement', 'Modern architecture principles', 'Positive', 3, null, 85),
('SL002', 'Product Manager', 'StartupInc', 2022, 'Product Manager', 'User retention dropping by 30%', 'Identify and fix retention issues', 'Conducted user research and A/B testing', 'Increased retention by 40%', 'Data-driven product decisions', 'Positive', 2, null, 78),
('SL003', 'Data Scientist', 'BigData Ltd', 2023, 'Data Scientist', 'Manual reporting taking 40 hours/week', 'Automate reporting pipeline', 'Built ML-powered dashboard', 'Reduced time to 2 hours/week', 'Automation saves significant time', 'Positive', 3, null, 92),
('SL004', 'DevOps Engineer', 'CloudFirst', 2021, 'DevOps Engineer', 'Deployment failures at 15% rate', 'Reduce deployment failure rate', 'Implemented CI/CD with automated testing', 'Reduced failures to 2%', 'Proper testing prevents failures', 'Positive', 2, null, 88),
('SL005', 'UX Designer', 'DesignStudio', 2022, 'UX Designer', 'User complaints about confusing navigation', 'Improve user experience', 'Redesigned information architecture', 'User satisfaction up 60%', 'User-centered design principles', 'Positive', 2, null, 82),
('SL006', 'Engineering Manager', 'TechGiant', 2023, 'Engineering Manager', 'Team missing sprint goals consistently', 'Improve team velocity and planning', 'Implemented agile best practices', 'Sprint success rate improved to 95%', 'Proper planning and communication', 'Positive', 3, null, 90),
('SL007', 'Marketing Manager', 'RetailCorp', 2022, 'Marketing Manager', 'Campaign ROI declining quarter over quarter', 'Optimize marketing spend', 'Implemented attribution modeling', 'ROI increased by 150%', 'Data-driven marketing decisions', 'Positive', 2, null, 86),
('SL008', 'Sales Engineer', 'SaaSVendor', 2023, 'Sales Engineer', 'Deal size decreasing and sales cycle lengthening', 'Improve sales process and deal quality', 'Created technical sales playbooks', 'Average deal size up 40%', 'Technical expertise accelerates sales', 'Positive', 2, null, 79),
('SL009', 'QA Engineer', 'MobileApp Co', 2021, 'QA Engineer', 'Bug escape rate to production at 12%', 'Reduce production bugs', 'Implemented shift-left testing strategy', 'Bug escape rate reduced to 3%', 'Early testing catches more issues', 'Positive', 2, null, 84),
('SL010', 'Backend Engineer', 'FinTech Inc', 2023, 'Backend Engineer', 'API response times averaging 2+ seconds', 'Optimize API performance', 'Implemented caching and database optimization', 'Response times reduced to 200ms average', 'Performance optimization techniques', 'Positive', 3, null, 91),
('SL011', 'Frontend Engineer', 'WebDev Agency', 2022, 'Frontend Engineer', 'Mobile conversion rate 40% lower than desktop', 'Improve mobile user experience', 'Redesigned mobile interface with progressive enhancement', 'Mobile conversion increased by 65%', 'Mobile-first design principles', 'Positive', 2, null, 87),
('SL012', 'Scrum Master', 'AgileTeam', 2023, 'Scrum Master', 'Team velocity declining for 3 sprints', 'Identify and remove impediments', 'Facilitated retrospectives and process improvements', 'Velocity increased by 30%', 'Continuous improvement mindset', 'Positive', 2, null, 76),
('SL013', 'Security Engineer', 'CyberSec Corp', 2022, 'Security Engineer', 'Security incident response time averaging 4 hours', 'Reduce incident response time', 'Automated threat detection and response', 'Response time reduced to 30 minutes', 'Automation improves security response', 'Positive', 3, null, 93),
('SL014', 'Data Engineer', 'Analytics Co', 2023, 'Data Engineer', 'Data pipeline failing 20% of the time', 'Improve pipeline reliability', 'Implemented monitoring and error handling', 'Pipeline reliability improved to 99.5%', 'Robust error handling and monitoring', 'Positive', 2, null, 89),
('SL015', 'Technical Writer', 'DocuTech', 2022, 'Technical Writer', 'Developer onboarding taking 2 weeks', 'Reduce onboarding time', 'Created interactive documentation and tutorials', 'Onboarding reduced to 3 days', 'Clear documentation accelerates learning', 'Positive', 1, null, 72),
('SL016', 'Cloud Architect', 'CloudNative Inc', 2023, 'Cloud Architect', 'Infrastructure costs increasing 25% monthly', 'Optimize cloud spend', 'Implemented cost monitoring and right-sizing', 'Reduced costs by 40%', 'Cloud cost optimization strategies', 'Positive', 3, null, 94),
('SL017', 'Mobile Developer', 'AppStudio', 2021, 'Mobile Developer', 'App store rating dropping to 2.8 stars', 'Improve app quality and user experience', 'Fixed critical bugs and improved UX', 'Rating improved to 4.6 stars', 'User feedback drives improvement', 'Positive', 2, null, 81),
('SL018', 'AI/ML Engineer', 'AITech', 2023, 'AI/ML Engineer', 'Model accuracy at 72% not meeting requirements', 'Improve model performance', 'Implemented feature engineering and ensemble methods', 'Accuracy improved to 89%', 'Feature engineering is crucial', 'Positive', 3, null, 95),
('SL019', 'Site Reliability Engineer', 'WebScale', 2022, 'Site Reliability Engineer', 'System uptime at 97% below SLA', 'Improve system reliability', 'Implemented chaos engineering and redundancy', 'Uptime improved to 99.9%', 'Proactive reliability engineering', 'Positive', 3, null, 92),
('SL020', 'Business Analyst', 'CorpSolutions', 2023, 'Business Analyst', 'Requirements gathering taking 6 weeks per project', 'Streamline requirements process', 'Created templates and facilitation frameworks', 'Requirements gathering reduced to 2 weeks', 'Structured processes improve efficiency', 'Positive', 1, null, 75);