-- Import final batch: stories 41-60
INSERT INTO interview_stories (
  star_l_id, role, organisation, year, theme, situation, task, action, result, lesson, 
  framing, tier, external_docs_url, score
) VALUES 
('SL041', 'Performance Analyst', 'SpeedAnalytics', 2021, 'Performance Analyst', 'Application bottlenecks unclear', 'Identify performance bottlenecks', 'Implemented APM and distributed tracing', 'Identified and resolved 15 bottlenecks', 'Observability reveals performance issues', 'Positive', 2, null, 86),
('SL042', 'Build Engineer', 'BuildMaster', 2023, 'Build Engineer', 'Build times taking 45 minutes', 'Reduce build times', 'Implemented distributed build system', 'Build times reduced to 5 minutes', 'Parallel builds improve efficiency', 'Positive', 2, null, 83),
('SL043', 'Technical Product Manager', 'ProductTech', 2022, 'Technical Product Manager', 'Feature adoption rate at 15%', 'Increase feature adoption', 'Implemented feature analytics and user feedback', 'Adoption rate increased to 75%', 'Data-driven feature development', 'Positive', 2, null, 79),
('SL044', 'Configuration Management', 'ConfigControl', 2023, 'Configuration Management', 'Configuration drift causing production issues', 'Eliminate configuration drift', 'Implemented GitOps and configuration as code', 'Configuration drift eliminated', 'GitOps ensures configuration consistency', 'Positive', 2, null, 87),
('SL045', 'Monitoring Engineer', 'MonitorAll', 2022, 'Monitoring Engineer', 'Alert fatigue reducing response effectiveness', 'Optimize alerting strategy', 'Implemented intelligent alerting with ML', 'False alerts reduced by 90%', 'Smart alerting improves response quality', 'Positive', 3, null, 90),
('SL046', 'Service Mesh Engineer', 'MeshTech', 2023, 'Service Mesh Engineer', 'Service communication causing latency', 'Optimize service mesh performance', 'Implemented optimized service mesh configuration', 'Service latency reduced by 50%', 'Service mesh optimization improves performance', 'Positive', 3, null, 94),
('SL047', 'Container Engineer', 'ContainerCorp', 2021, 'Container Engineer', 'Container orchestration complexity', 'Simplify container management', 'Implemented standardized Kubernetes patterns', 'Deployment complexity reduced significantly', 'Standards simplify operations', 'Positive', 2, null, 85),
('SL048', 'Event Streaming Engineer', 'StreamData', 2023, 'Event Streaming Engineer', 'Data processing lag affecting real-time features', 'Reduce data processing latency', 'Optimized event streaming architecture', 'Processing latency reduced by 80%', 'Stream processing optimization techniques', 'Positive', 3, null, 93),
('SL049', 'API Gateway Engineer', 'GatewayTech', 2022, 'API Gateway Engineer', 'API management overhead slowing development', 'Streamline API lifecycle', 'Implemented automated API governance', 'API deployment time reduced by 70%', 'Automation streamlines API management', 'Positive', 2, null, 88),
('SL050', 'Compliance Engineer', 'CompliTech', 2023, 'Compliance Engineer', 'Compliance audits taking 3 months', 'Accelerate compliance processes', 'Automated compliance monitoring and reporting', 'Audit preparation reduced to 2 weeks', 'Automation enables continuous compliance', 'Positive', 2, null, 84),
('SL051', 'Disaster Recovery Specialist', 'DisasterPrep', 2022, 'Disaster Recovery Specialist', 'RTO at 8 hours not meeting business needs', 'Improve disaster recovery capabilities', 'Designed automated DR with hot standby', 'RTO reduced to 15 minutes', 'Automation enables fast recovery', 'Positive', 3, null, 96),
('SL052', 'Capacity Planning Engineer', 'CapacityPro', 2023, 'Capacity Planning Engineer', 'Resource utilization at 90% causing instability', 'Optimize resource utilization', 'Implemented predictive capacity planning', 'Utilization optimized to 70% with better performance', 'Predictive planning prevents bottlenecks', 'Positive', 2, null, 89),
('SL053', 'Service Delivery Manager', 'DeliverService', 2021, 'Service Delivery Manager', 'Service delivery SLA at 85%', 'Improve service delivery performance', 'Implemented service management automation', 'SLA improved to 99%', 'Process automation improves service delivery', 'Positive', 2, null, 81),
('SL054', 'Technical Evangelist', 'EvangelTech', 2023, 'Technical Evangelist', 'Developer community engagement low', 'Increase developer engagement', 'Created comprehensive developer experience program', 'Developer engagement increased by 300%', 'Good developer experience drives adoption', 'Positive', 1, null, 77),
('SL055', 'Edge Computing Engineer', 'EdgeTech', 2022, 'Edge Computing Engineer', 'Edge deployment complexity limiting rollouts', 'Simplify edge deployments', 'Built automated edge deployment framework', 'Edge deployment time reduced by 85%', 'Automation enables edge scalability', 'Positive', 3, null, 92),
('SL056', 'Workflow Engineer', 'WorkflowPro', 2023, 'Workflow Engineer', 'Business process automation failing 25% of time', 'Improve workflow reliability', 'Implemented robust error handling and monitoring', 'Workflow success rate improved to 99%', 'Robust design improves reliability', 'Positive', 2, null, 86),
('SL057', 'Data Platform Engineer', 'DataPlatform', 2022, 'Data Platform Engineer', 'Data scientists waiting 2 weeks for environments', 'Accelerate data science workflows', 'Built self-service data science platform', 'Environment provisioning reduced to 5 minutes', 'Self-service platforms improve productivity', 'Positive', 3, null, 91),
('SL058', 'Serverless Engineer', 'ServerlessTech', 2023, 'Serverless Engineer', 'Cold start latency affecting user experience', 'Optimize serverless performance', 'Implemented warming strategies and optimization', 'Cold start latency reduced by 70%', 'Serverless optimization techniques', 'Positive', 2, null, 88),
('SL059', 'GitOps Engineer', 'GitOpsPro', 2021, 'GitOps Engineer', 'Deployment consistency issues across environments', 'Ensure deployment consistency', 'Implemented GitOps with environment promotion', 'Deployment consistency achieved across all environments', 'GitOps ensures consistent deployments', 'Positive', 3, null, 94),
('SL060', 'Observability Engineer', 'ObserveTech', 2023, 'Observability Engineer', 'Troubleshooting incidents taking 3+ hours', 'Reduce incident resolution time', 'Implemented unified observability platform', 'Incident resolution time reduced to 20 minutes', 'Observability accelerates troubleshooting', 'Positive', 3, null, 95);