-- Import stories 21-40
INSERT INTO interview_stories (
  star_l_id, role, organisation, year, theme, situation, task, action, result, lesson, 
  framing, tier, external_docs_url, score
) VALUES 
('SL021', 'Integration Engineer', 'ConnectAll', 2022, 'Integration Engineer', 'Integration failures causing daily production issues', 'Stabilize integration layer', 'Implemented circuit breakers and retry logic', 'Integration failures reduced by 95%', 'Resilient integration patterns', 'Positive', 2, null, 88),
('SL022', 'Performance Engineer', 'SpeedTech', 2023, 'Performance Engineer', 'Application load time at 8 seconds', 'Optimize application performance', 'Implemented performance monitoring and optimization', 'Load time reduced to 1.2 seconds', 'Performance monitoring guides optimization', 'Positive', 3, null, 90),
('SL023', 'Release Manager', 'DeployFast', 2021, 'Release Manager', 'Release cycle taking 6 weeks', 'Accelerate release process', 'Implemented automated deployment pipeline', 'Release cycle reduced to 2 weeks', 'Automation accelerates delivery', 'Positive', 2, null, 83),
('SL024', 'Technical Lead', 'InnovateNow', 2023, 'Technical Lead', 'Code quality issues causing 30% of bugs', 'Improve code quality', 'Implemented code review process and static analysis', 'Bug rate reduced by 70%', 'Code quality practices prevent issues', 'Positive', 2, null, 87),
('SL025', 'Infrastructure Engineer', 'BuildIt', 2022, 'Infrastructure Engineer', 'Server provisioning taking 3 days', 'Automate infrastructure provisioning', 'Implemented Infrastructure as Code', 'Provisioning reduced to 30 minutes', 'Infrastructure automation saves time', 'Positive', 2, null, 86),
('SL026', 'API Developer', 'ServiceMesh', 2023, 'API Developer', 'API documentation outdated and incomplete', 'Improve API documentation', 'Implemented automated API documentation', 'Developer adoption increased by 200%', 'Good documentation drives adoption', 'Positive', 1, null, 74),
('SL027', 'Test Automation Engineer', 'QualityFirst', 2022, 'Test Automation Engineer', 'Manual testing taking 40 hours per release', 'Automate testing process', 'Built comprehensive test automation framework', 'Testing time reduced to 4 hours', 'Test automation improves efficiency', 'Positive', 2, null, 85),
('SL028', 'Platform Engineer', 'PlatformTech', 2023, 'Platform Engineer', 'Developer productivity declining due to tooling', 'Improve developer experience', 'Built internal developer platform', 'Developer velocity increased by 50%', 'Good tooling improves productivity', 'Positive', 3, null, 91),
('SL029', 'Database Administrator', 'DataCore', 2021, 'Database Administrator', 'Database performance degrading under load', 'Optimize database performance', 'Implemented indexing and query optimization', 'Query performance improved by 400%', 'Database optimization techniques', 'Positive', 2, null, 88),
('SL030', 'Network Engineer', 'NetSecure', 2023, 'Network Engineer', 'Network latency causing user complaints', 'Reduce network latency', 'Optimized routing and implemented CDN', 'Latency reduced by 60%', 'Network optimization improves user experience', 'Positive', 2, null, 82),
('SL031', 'Solutions Architect', 'EnterpriseTech', 2022, 'Solutions Architect', 'System integration complexity increasing costs', 'Simplify integration architecture', 'Designed microservices architecture with API gateway', 'Integration costs reduced by 45%', 'Simple architectures reduce complexity', 'Positive', 3, null, 93),
('SL032', 'Cybersecurity Analyst', 'SecureNet', 2023, 'Cybersecurity Analyst', 'Security alerts overwhelming team', 'Optimize security monitoring', 'Implemented AI-based threat detection', 'False positives reduced by 80%', 'AI improves security efficiency', 'Positive', 2, null, 89),
('SL033', 'DevSecOps Engineer', 'SecureDev', 2022, 'DevSecOps Engineer', 'Security vulnerabilities found late in cycle', 'Shift security left in development', 'Integrated security scanning in CI/CD pipeline', 'Vulnerabilities caught 90% earlier', 'Early security integration prevents issues', 'Positive', 3, null, 94),
('SL034', 'Systems Engineer', 'SystemsInc', 2023, 'Systems Engineer', 'System monitoring blind spots causing outages', 'Improve system observability', 'Implemented comprehensive monitoring and alerting', 'Mean time to detection reduced by 85%', 'Observability prevents outages', 'Positive', 2, null, 87),
('SL035', 'Software Architect', 'ArchitectureFirm', 2021, 'Software Architect', 'Monolithic application limiting scalability', 'Design scalable architecture', 'Migrated to event-driven microservices', 'System can now handle 10x load', 'Event-driven architecture enables scale', 'Positive', 3, null, 96),
('SL036', 'Technical Consultant', 'ConsultCorp', 2023, 'Technical Consultant', 'Client systems integration taking 6 months', 'Accelerate integration delivery', 'Created reusable integration framework', 'Integration time reduced to 6 weeks', 'Reusable frameworks accelerate delivery', 'Positive', 2, null, 84),
('SL037', 'Automation Engineer', 'AutoTech', 2022, 'Automation Engineer', 'Manual processes consuming 60% of team time', 'Automate repetitive processes', 'Built workflow automation platform', 'Manual work reduced by 80%', 'Automation frees teams for value work', 'Positive', 2, null, 88),
('SL038', 'Cloud Developer', 'CloudNative', 2023, 'Cloud Developer', 'Cloud costs spiraling out of control', 'Implement cost governance', 'Built cost monitoring and automated rightsizing', 'Costs reduced by 50% while improving performance', 'Cost governance enables sustainable growth', 'Positive', 3, null, 92),
('SL039', 'Reliability Engineer', 'ReliableSystem', 2022, 'Reliability Engineer', 'Mean time to recovery at 4 hours', 'Reduce system recovery time', 'Implemented automated failover and recovery', 'MTTR reduced to 15 minutes', 'Automation improves recovery times', 'Positive', 3, null, 95),
('SL040', 'Integration Specialist', 'ConnectPro', 2023, 'Integration Specialist', 'Data synchronization errors affecting business', 'Ensure data consistency', 'Implemented event sourcing and CQRS pattern', 'Data consistency issues eliminated', 'Event sourcing ensures data integrity', 'Positive', 3, null, 91);