// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pflisxkcxbzboxwidywf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmbGlzeGtjeGJ6Ym94d2lkeXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzMwNTgsImV4cCI6MjA1ODIwOTA1OH0.wv3NvIapXMK49aj7XNrWavWzXJi64nxSQEfPSJBvIeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});